/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.FormaMod;
import domen.Korisnik;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import session.Session;
/**
 *
 * @author User
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        centrirajFormu();
       setTrenutnogKorisnika();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblPrijavljeniKorisnik = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPozadina = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemUnos = new javax.swing.JMenuItem();
        menuItemPretraga = new javax.swing.JMenuItem();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrijavljeniKorisnik.setFont(new java.awt.Font("Lao UI", 2, 18)); // NOI18N
        getContentPane().add(lblPrijavljeniKorisnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 210, 20));

        jLabel1.setFont(new java.awt.Font("Lao UI", 2, 18)); // NOI18N
        jLabel1.setText("Prijavljeni korisnik: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        lblPozadina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPozadina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/pozadina2.png"))); // NOI18N
        getContentPane().add(lblPozadina, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jMenu1.setText("Angazovanje");

        menuItemUnos.setText("Unos");
        menuItemUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUnosActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemUnos);

        menuItemPretraga.setText("Pretraga");
        menuItemPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretragaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemPretraga);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUnosActionPerformed
        // TODO add your handling code here:
        UnosAngazovanjaForma uaf = new UnosAngazovanjaForma(null, true, FormaMod.NOVO);
        uaf.setVisible(true);
    }//GEN-LAST:event_menuItemUnosActionPerformed

    private void menuItemPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretragaActionPerformed
        // TODO add your handling code here:
        PretragaAngazovanjaForma paf = new PretragaAngazovanjaForma(null, true);
        paf.setVisible(true);
    }//GEN-LAST:event_menuItemPretragaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       this.setExtendedState(JFrame.MAXIMIZED_BOTH );
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblPozadina;
    private javax.swing.JLabel lblPrijavljeniKorisnik;
    private javax.swing.JMenuItem menuItemPretraga;
    private javax.swing.JMenuItem menuItemUnos;
    // End of variables declaration//GEN-END:variables

    private void setTrenutnogKorisnika() {
        Korisnik korisnik = Session.getInstance().getTrenutniKorisnik();
        lblPrijavljeniKorisnik.setText(korisnik.getIme()+" "+ korisnik.getPrezime());
    }

    private void centrirajFormu() {
        this.setLocationRelativeTo(null);
    }
}
